
name: hello action
description: returns hello <person>, where peson is optional and defaults to world

inputs:
  person:
    description: 'person to say hello to'
    required: false
    default: 'world'

runs:
  using: 'composite'
  steps:
    - name: hello
      shell: bash
      run: echo hello ${{ inputs.person }}

