name: test hello

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: test workflow default
        uses: dennisyau1885/hello@main

      - name: test workflow custom
        uses: dennisyau1885/hello@main
        with:
          person: 'bob'

