name: test hello

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

#      - name: test workflow default
#        uses: ./

      - name: test workflow custom
        uses: ./
        with:
          person: 'bob'

