name: test hello

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: test workflow default
        uses: dennisyau1885/hello@v1

      - name: test workflow custom
        uses: dennisyau1885/hello@v1
        with:
          person: 'bob'

      - name: test workflow custom v2
        uses: dennisyau1885/hello@v2
        with:
          person: 'baz'

